### ISSUE TITLE
Create Backend

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/chonkerU#32]
* improve search, filter, and enable more features by having a backend
* oracle cloud is apparently free so try that
* node.Js backend with MongoDB database for work practice
* try adding 4th year prediction

**Comment by zakuArbor** [comment]
## API Routes
Only get requests allowed

`/course/<course_id>`: grab general course information
`/course/<course_id>/brief`: grab brief info about the course such as course desc and title
`/courses/`: grab all courses name and code
`/profs/`: grab all prof names
`/prof/<prof_id>`: grab prof info
`/blogs/`: links to course reviews of the course

**Comment by dannysheridan** [comment]
@zakuArbor   have you considered going schema-first and auto-generating the networking logic & types on the backend? our open source project supports Express if that's the server framework you've picked: www.buildwithfern.com

**Comment by zakuArbor** [comment]
> @zakuArbor have you considered going schema-first and auto-generating the networking logic & types on the backend? our open source project supports Express if that's the server framework you've picked: [www.buildwithfern.com](http://www.buildwithfern.com)

@dannysheridan thanks for introducing me to your project. At this moment, I will avoid using a tool for auto-generating as it's best for me to practice the old fashion way and experiment for learning purposes. I hope for the best and success for your project.
